apiVersion: v1
kind: Pod
metadata:
  name: opendidac-web
  namespace: opendidac
  labels:
    app: opendidac-web
spec:
  initContainers:
    - name: prisma-migrate
      image: opendidac/web:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: opendidac-app-secret
      workingDir: /app
      command: ["sh", "-c"]
      args:
        - >
          for i in $(seq 1 30); do
            npx prisma migrate deploy && exit 0;
            echo 'DB not ready, retrying...';
            sleep 5;
          done;
          exit 1
  containers:
    - name: web
      image: opendidac/web:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 3000
      envFrom:
        - secretRef:
            name: opendidac-app-secret
      readinessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
