apiVersion: v1
kind: Secret
metadata:
  name: opendidac-app-secret
  namespace: opendidac
  labels:
    app: opendidac-web
type: Opaque
stringData:
  DATABASE_URL: "postgresql://eval-dev:eval-dev@postgres:5432/eval-dev"
  NEXTAUTH_URL: "http://opendidac.local"
  NEXTAUTH_SECRET: "change-me"
  NEXTAUTH_SWITCH_CLIENT_ID: "change-me"
  NEXTAUTH_SWITCH_CLIENT_SECRET: "change-me"
  NEXTAUTH_SWITCH_ORGANIZATION_DOMAINS: "@example.org"
