apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: opendidac
  labels:
    app: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "change-me"
